### ISSUE TITLE
After running an EXE, the EXE's grandparent folder cannot be accessed.

### ISSUE THREAD

**Issue by Wowfunhappy** [openzfsonwindows/ZFSin#116]
I have a pool mounted as read only with the latest "Vegnest" release, in Windows 10 1607.

Let's say the pool's directory structure is as follows:

* volume root
  * Foo
  * Bar
    * Foobar
      * Barfoo.exe

After running Barfoo.exe, the Bar folder cannot be accessed. Attempting to open it in Windows Explorer results in an "Access is denied." error message.

The volume root, however, can still be accessed, as can the Foo directory.

**Comment by lundman** [comment]
I believe we fixed the Access is denied problem a day or so after that release, I have created a 0.17 release so you can more easily find it.

**Comment by Wowfunhappy** [comment]
Thanks, I appreciate that! However, I'm actually still encountering the issue in 0.17. It consistently happens when an exe is run, and seemingly never otherwise.

**Comment by lundman** [comment]
Yes, this is confirmed. It appears to be because `Bar`'s parent is root ("/"), the mount of ZFS. Whereas if you just put the .exe one directory lower: `Bar/Foobar/Foo/file.exe` it does not appear to trigger here.

Not sure if Root's security_descriptor is not set, set correctly, or we just look it up incorrectly when returning Root.

**Comment by lundman** [comment]
Not sure about this one, but I had marginal success with the new branch.

http://www.lundman.net/OpenZFSOnWindows-debug-20190312.exe

**Comment by vmlemon** [comment]
I had fun, trying to install ActivePerl 5.6.1.635 (old, but I wanted to see if I could run the Symbian^4 emulator, which requires it, on ZFS), on the root of my ZFS dataset, both with the new build, and the previous build - although the newer build gets further. 

As a side note, the Security tab says:

> No permissions have been assigned for this object.
> 
> Warning: this is a potential security risk because anyone who can access this object can take ownership of it. The object’s owner should assign permissions as soon as possible
> 

(No permissions are assigned, by default, to the root of the dataset, supposedly)

In both cases, the installer would get as far as creating directories, before bailing with an error, stating that it couldn't create a directory (even though was just created), and if I changed the permissions on the newly-created directory to "Owner: Everyone", it would get a little further, before complaining about another directory (which I'd go back, and change the permissions on, ad infinitum - with the new version, Explorer would say that it was unable to set the permissions on subdirectories, if I set it to propagate the new ownership on files/containers), and eventually (with the old version), it would claim to have installed everything, only to automatically start trying to roll the process back, and get stuck midway.

With the new version, if I changed the ownership of the root of the dataset to "Everyone", it'd get propagated to child objects (until rebooting, when that info would be lost), and I was able to make the installer hang my PC, and eventually BSOD/reboot itself, trying to do a reinstall.

That version of ActivePerl can still be found at https://www.mediafire.com/folder/79jhy594xb3uk/Symbian_Development#uixx0dkp08xlp, and I'm attaching the MiniDump, if it helps.

[031219-14750-01.zip](https://github.com/openzfsonwindows/ZFSin/files/2957114/031219-14750-01.zip)

**Comment by vmlemon** [comment]
Managed to get a SYSTEM_SERVICE_EXCEPTION, trying to download a file, with Chrome, too, with 20190312.

[031219-12437-01.zip](https://github.com/openzfsonwindows/ZFSin/files/2957824/031219-12437-01.zip)

**Comment by lundman** [comment]
So ah, we saying better, or worse, or just different? The BSODs aside (those are just bugs) do the AccessDenied still persist? At the moment, the top/root node gets these permissions set:

```
+static sid_header sid_BA =  // BUILTIN\Administrators
+static sid_header sid_SY =  // NT AUTHORITY\SYSTEM
+static sid_header sid_BU = // BUILTIN\Users
+static sid_header sid_AU = // NT AUTHORITY\Authenticated Users

+       { 0, FILE_ALL_ACCESS, &sid_BA },
+       { OBJECT_INHERIT_ACE | CONTAINER_INHERIT_ACE | INHERIT_ONLY_ACE, FILE_ALL_ACCESS, &sid_BA },
+       { 0, FILE_ALL_ACCESS, &sid_SY },
+       { OBJECT_INHERIT_ACE | CONTAINER_INHERIT_ACE | INHERIT_ONLY_ACE, FILE_ALL_ACCESS, &sid_SY },
+       { OBJECT_INHERIT_ACE | CONTAINER_INHERIT_ACE, FILE_ALL_ACCESS, &sid_BU },
+       { OBJECT_INHERIT_ACE | CONTAINER_INHERIT_ACE | INHERIT_ONLY_ACE, FILE_GENERIC_READ | FILE_GENERIC_WRITE | FILE_GENERIC_EXECUTE | DELETE, &sid_AU },
+       { 0, FILE_GENERIC_READ | FILE_GENERIC_WRITE | FILE_GENERIC_EXECUTE | DELETE, &sid_AU },
```

**Comment by vmlemon** [comment]
Different, mostly. There's no real pattern as to how the installer touches files, as it worms its way through the FS - not every directory will cause "Access Denied" to be thrown, or cause complaints about being unable to create files/directories. (The symptom still manifests, for the affected directories, as them having no ownership/permission ACLs, in Windows Explorer).

The "Access Denied" errors still happen - I recursively get locked out of various directories, in G:\Perl\lib, and G:\Perl\site, as the installer works its way through its payload, and I have to manually set the ownership of each directory that it touches, to "Everyone", in order to make it progress further.

As another swerve (guessing that there's similar issues at play), that build also introduces regressions in VHD-handling, compared to 20190307 - so now, instead of happily mounting, after being double-clicked, Explorer now gives a generic "Couldn't Mount File : Sorry, there was a problem mounting the file" error.

**Comment by lundman** [comment]
Could be too issues in here though, one is that we didn't set anything at all, and it would lose its mind - which what I tried to address.

There could also be a bug with SetSecurity, where programs/users try to SetSecurity will cause similar problems. It sounds like the Installer you use is calling SetSecurity

**Comment by Wowfunhappy** [comment]
Are these the same issue at all?

My ZFS pool is mounted as read-only, so the issue was cropping files without _any_ files being written whatsoever (unless something was very screwed up).

(Thanks for the new build by the way, though I haven't had a chance to test it and may not for a while.)

**Comment by vmlemon** [comment]
As for manually setting ACLs, you can't recursively set them (at least for Effective Ownership), in Explorer, with this build, with "Replace owner on subcontainers, and objects", since you end up getting:
![image](https://user-images.githubusercontent.com/35642/54249144-002d5700-4537-11e9-932f-631bfb602f0d.png), and if you click through, you end up with:
![image](https://user-images.githubusercontent.com/35642/54249158-0a4f5580-4537-11e9-87d7-8a0d4f39d38f.png).

If you keep clicking "Continue", it gets stuck in a loop, until you hit "Cancel", which gives you:
![image](https://user-images.githubusercontent.com/35642/54249190-2d7a0500-4537-11e9-8b93-7a389d306674.png), and you have to cancel every dialogue, to avoid the Groundhog Day simulation. :(

**Comment by lundman** [comment]
Perhaps the trick first is to check what default Security settings a clean mounted volume gets with NTFS, and start with that. 

Then look at why it goes wrong if SetSecurity is called.

**Comment by vmlemon** [comment]
On a virgin NTFS disk, I get this, with PowerShell's `Get-Acl` command, at the root of the volume:
<pre>
PS C:\Windows\system32> Get-Acl  D:


    Directory:


Path Owner               Access
---- -----               ------
D:\  NT AUTHORITY\SYSTEM NT AUTHORITY\Authenticated Users Allow  -536805376...
</pre>

With `icacls`:
<pre>
PS C:\Windows\system32> icacls D:
D: BUILTIN\Administrators:(F)
   BUILTIN\Administrators:(OI)(CI)(IO)(F)
   NT AUTHORITY\SYSTEM:(F)
   NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
   NT AUTHORITY\Authenticated Users:(M)
   NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(M)
   BUILTIN\Users:(RX)
   BUILTIN\Users:(OI)(CI)(IO)(GR,GE)

Successfully processed 1 files; Failed processing 0 files
</pre>

**Comment by vmlemon** [comment]
With my ZFS dataset, I get:

<pre>
PS C:\Windows\system32> icacls G:
G:  No permissions are set. All users have full control.
Successfully processed 1 files; Failed processing 0 files
</pre>

<pre>
PS C:\Windows\system32> Get-Acl G:


    Directory:


Path Owner               Access
---- -----               ------
G:\  NT AUTHORITY\SYSTEM Everyone Allow  -1
</pre>

**Comment by lundman** [comment]
Ah - I did suspect that we fail to set anything on the Volume itself "G:" whereas we set it in ZFS on "/" - I guess that would be G:\.

I should check if I can figure out how to set the Volumes Security

**Comment by vmlemon** [comment]
Yup, G:\ is the ZFS dataset, and D:\ is the temporary NTFS disk image. :)

**Comment by lundman** [comment]
Hmm So my ZFS E:
```
icacls E:
E: BUILTIN\Administrators:(F)
   BUILTIN\Administrators:(OI)(CI)(IO)(F)
   NT AUTHORITY\SYSTEM:(F)
   NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
   BUILTIN\Users:(OI)(CI)(F)
   NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(RX,W)
   NT AUTHORITY\Authenticated Users:(RX,W)

Successfully processed 1 files; Failed processing 0 files
```

So you were probably not running yesterday's cut. Which means we are correctly setting Security on Volumes

**Comment by vmlemon** [comment]
As for the ActivePerl issue, I got this log, from FileSpy, from a retry attempt, after hitting the "An error occurred while attempting to write the directory G:\Perl1\lib" error:
<pre>#	Time sent	Request	Path	Status	More info
1	03:06:49.916	IRP_MJ_NETWORK_QUERY_OPEN	G:	STATUS_FLT_DISALLOW_FAST_IO	FileNetworkOpenInformation CreateTime: FFFFA686-7826A5C0 LastAccTime: 0 LastWrtTime: 000001F2-0AB98308 ChangeTime: 0 AllocationSize: 000001F2-0C1900E0 EndOfFile: 00000000-00000000 Attrib: 00020000
2	03:06:49.916	IRP_MJ_CREATE	G:\Perl1	STATUS_SUCCESS	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
3	03:06:49.916	IRP_MJ_QUERY_INFORMATION	G:\Perl1	STATUS_FLT_DISALLOW_FAST_IO	FileNetworkOpenInformation
4	03:06:49.916	IRP_MJ_QUERY_INFORMATION	G:\Perl1	STATUS_SUCCESS	FileNetworkOpenInformation CreateTime: 01D4D948-51DFAE43 LastAccTime: 01D4D948-51DFAE43 LastWrtTime: 01D4D948-52860F4F ChangeTime: 01D4D948-52860F4F AllocationSize: 00000000-00001000 EndOfFile: 00000000-00000000 Attrib: 00000010
5	03:06:49.916	IRP_MJ_CLEANUP	G:\Perl1	STATUS_SUCCESS	
6	03:06:49.916	IRP_MJ_CLOSE	G:\Perl1	STATUS_SUCCESS	
7	03:06:49.916	IRP_MJ_NETWORK_QUERY_OPEN	G:	STATUS_FLT_DISALLOW_FAST_IO	FileNetworkOpenInformation CreateTime: 01D4D948-51DFAE43 LastAccTime: 0 LastWrtTime: 01D4D948-52860F4F ChangeTime: 01D4D948-52860F4F AllocationSize: 00000000-00001000 EndOfFile: 00000000-00000000 Attrib: 00000010
8	03:06:49.917	IRP_MJ_CREATE	G:	STATUS_ACCESS_DENIED	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
9	03:06:49.917	IRP_MJ_CREATE	G:	STATUS_OBJECT_NAME_COLLISION	FILE_CREATE CreOpts: 00200021 Access: 00100001 Share:  00000003 Attrib: 00000080
10	03:06:49.917	IRP_MJ_NETWORK_QUERY_OPEN	G:	STATUS_FLT_DISALLOW_FAST_IO	FileNetworkOpenInformation CreateTime: 01D4D948-00100001 LastAccTime: 0 LastWrtTime: 0 ChangeTime: FFFFD30A-B55F59B0 AllocationSize: C0000035-00001001 EndOfFile: FFFFA686-78FD5440 Attrib: 0
11	03:06:49.918	IRP_MJ_CREATE	G:	STATUS_ACCESS_DENIED	FILE_OPEN CreOpts: 00200000 Access: 00000080 Share:  00000007 Attrib: 0
</pre>

The `STATUS_OBJECT_NAME_COLLISION` seems curious to me, but it looks like the installer hammers the disk pretty hard, with `IRP_MJ_CREATE` operations, on the root, even during the launch, so it was a pain to get a log, this clean.

**Comment by vmlemon** [comment]
> Hmm So my ZFS E:
> 
> ```
> icacls E:
> E: BUILTIN\Administrators:(F)
>    BUILTIN\Administrators:(OI)(CI)(IO)(F)
>    NT AUTHORITY\SYSTEM:(F)
>    NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
>    BUILTIN\Users:(OI)(CI)(F)
>    NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(RX,W)
>    NT AUTHORITY\Authenticated Users:(RX,W)
> 
> Successfully processed 1 files; Failed processing 0 files
> ```
> So you were probably not running yesterday's cut. Which means we are correctly setting Security on Volumes
> 
> Although we clearly do differ.

Interesting. Going to uninstall all of the OpenZFS stuff, reboot, and retry reinstalling that build, to make sure that there's nothing odd going on - I don't think that running the latest installer, to try upgrading, when OZFS is already installed cleans everything up, as I'd expect it to, then...

**Comment by lundman** [comment]
Never tried myself, it is supposed to tell you to reboot - but you can uninstall / reinstall without boot manually - something we should polish at some point.  Technically, the installer should export all pools, unload SYS, install, load SYS and re-import :)

**Comment by vmlemon** [comment]
Uninstalled, and reinstalled 20190312, and now my ZFS dataset has returned to the list of storage locations, in "Default save locations", and `icacls` reports:
<pre>
C:\Windows\system32>icacls G:
G:  No permissions are set. All users have full control.
Successfully processed 1 files; Failed processing 0 files
</pre>

The ActivePerl installer gets as far as:
![image](https://user-images.githubusercontent.com/35642/54298562-e0d31000-45b0-11e9-9bfd-97255dc8f042.png)
Before it starts complaining.

Windows Explorer reports:
![image](https://user-images.githubusercontent.com/35642/54298632-052eec80-45b1-11e9-879d-194343a5a8b5.png)

![image](https://user-images.githubusercontent.com/35642/54298675-1aa41680-45b1-11e9-9c87-707ad7eeb136.png)

<pre>
C:\Windows\system32>icacls G:\Perl6\lib\Pod
G:\Perl6\lib\Pod: Access is denied.
Successfully processed 0 files; Failed processing 1 files
</pre>

If I hit "Continue", I get the list of ACLs:
<pre>
C:\Windows\system32>icacls G:\Perl6\lib\Pod
G:\Perl6\lib\Pod BUILTIN\Administrators:(F)
                 NT AUTHORITY\SYSTEM:(F)
                 NT AUTHORITY\LogonSessionId_0_329993:(RX)

Successfully processed 1 files; Failed processing 0 files
</pre>
...until it locks up another directory...

**Comment by vmlemon** [comment]
I have found that some executables won't even launch, now, though. FileSpy says that certain OpLock features aren't implemented, and Explorer says nothing (although the VLC installer will get as far as UAC elevation, before unceremoniously dying).

[VLCFail.zip](https://github.com/openzfsonwindows/ZFSin/files/2962774/VLCFail.zip)
[NoOpLock.zip](https://github.com/openzfsonwindows/ZFSin/files/2962775/NoOpLock.zip)

**Comment by vmlemon** [comment]
Was able to install FireFox Portable, after removing Sandboxie; although the ActivePerl installer still fails, even after temporarily disabling Windows Defender. 

Managed to get a FileSpy log, of that installer, until the point that it fails, though...

[ActivePerl1.zip](https://github.com/openzfsonwindows/ZFSin/files/2964281/ActivePerl1.zip)

**Comment by vmlemon** [comment]
The FireFox doesn't launch (because of WinSXS errors), but it also doesn't break the file system permissions.   Would probably have to revert to 0.17/0.16, and try tracing that, whilst trying to reproduce the issue.

The "Perl6" directory (from the last ActivePerl Installer run) does now throw the "Access is denied" error, when I try to open it, though - icacls says:
<pre>
C:\Windows\system32>icacls G:\Perl6
G:\Perl6: Access is denied.
Successfully processed 0 files; Failed processing 1 files
</pre>

I also get "Access is denied", when trying to enter it using "cd G:\Perl6", from a shell; and, looking at FileSpy, I see quite a lot of "STATUS_PRIVILEGE_NOT_HELD", when trying to view the ACLs, from within Windows Explorer.

Managed to get a trace of that, and what happens, when trying to recursively change ownership (which predictably fails, too).

[Perl6_ACL_Fail.zip](https://github.com/openzfsonwindows/ZFSin/files/2964324/Perl6_ACL_Fail.zip)

Might be worth the original poster grabbing a copy of FileSpy, from http://www.zezula.net/en/fstools/filespy.html, and getting some logs, too?

**Comment by Wowfunhappy** [comment]
> Not sure about this one, but I had marginal success with the new branch.
> 
> http://www.lundman.net/OpenZFSOnWindows-debug-20190312.exe

With regard to the core issue, I'm not having any luck with this on my end. Folder still becomes inaccessible after running exe.

**Comment by lundman** [comment]
Ok I had moderate success with 0404 test https://openzfsonosx.org/wiki/Windows_builds#Nightly_builds

See how that runs for you.

**Comment by Wowfunhappy** [comment]
The new build appears to have fully solved the problem for me!

**Comment by fire** [comment]
Is this closed?

Can you open a new issue for "EXE's take a very long time to start now"?

**Comment by Wowfunhappy** [comment]
Closed now. I only left it open because even though it was working for me, @lundman mentioned he'd had "Moderate" success, I wasn't sure what that meant.
